/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kostan.ku;

/**
 *
 * @author Aulia
 */
public class KostRedNew extends javax.swing.JFrame {

    /**
     * Creates new form KostRedNew
     */
    public KostRedNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAtas = new javax.swing.JPanel();
        judulKost = new javax.swing.JLabel();
        roomlist = new javax.swing.JLabel();
        panelBawah = new javax.swing.JPanel();
        angka1 = new javax.swing.JLabel();
        angka2 = new javax.swing.JLabel();
        angka3 = new javax.swing.JLabel();
        labelWM = new javax.swing.JLabel();
        btnJasmine = new javax.swing.JButton();
        btnTulip = new javax.swing.JButton();
        btnAnggrek = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAtas.setBackground(new java.awt.Color(226, 252, 226));

        judulKost.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        judulKost.setForeground(new java.awt.Color(255, 153, 153));
        judulKost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulKost.setText("Red Rose Kost");

        roomlist.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        roomlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomlist.setText("Room List");

        panelBawah.setBackground(new java.awt.Color(235, 235, 254));

        angka1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 12)); // NOI18N
        angka1.setForeground(new java.awt.Color(153, 153, 255));
        angka1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        angka1.setText("1.");

        angka2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 12)); // NOI18N
        angka2.setForeground(new java.awt.Color(153, 153, 255));
        angka2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        angka2.setText("2.");

        angka3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 12)); // NOI18N
        angka3.setForeground(new java.awt.Color(153, 153, 255));
        angka3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        angka3.setText("3.");

        labelWM.setFont(new java.awt.Font("Serif", 3, 11)); // NOI18N
        labelWM.setForeground(new java.awt.Color(153, 153, 255));
        labelWM.setText("Kostan-Ku : Kukusan UI");

        btnJasmine.setBackground(new java.awt.Color(255, 204, 204));
        btnJasmine.setFont(new java.awt.Font("Segoe UI Semibold", 2, 11)); // NOI18N
        btnJasmine.setForeground(new java.awt.Color(255, 102, 102));
        btnJasmine.setText("Jasmine Room");
        btnJasmine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJasmineActionPerformed(evt);
            }
        });

        btnTulip.setBackground(new java.awt.Color(255, 204, 204));
        btnTulip.setFont(new java.awt.Font("Segoe UI Semibold", 2, 11)); // NOI18N
        btnTulip.setForeground(new java.awt.Color(255, 102, 102));
        btnTulip.setText("Tulip Room");
        btnTulip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTulipActionPerformed(evt);
            }
        });

        btnAnggrek.setBackground(new java.awt.Color(255, 204, 204));
        btnAnggrek.setFont(new java.awt.Font("Segoe UI Semibold", 2, 11)); // NOI18N
        btnAnggrek.setForeground(new java.awt.Color(255, 102, 102));
        btnAnggrek.setText("Anggrek Room");
        btnAnggrek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnggrekActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 3, 12)); // NOI18N
        btnBack.setText("BACK");
        btnBack.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBawahLayout = new javax.swing.GroupLayout(panelBawah);
        panelBawah.setLayout(panelBawahLayout);
        panelBawahLayout.setHorizontalGroup(
            panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBawahLayout.createSequentialGroup()
                .addGroup(panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBawahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelBawahLayout.createSequentialGroup()
                                .addComponent(angka1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnJasmine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelBawahLayout.createSequentialGroup()
                                .addComponent(angka3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnAnggrek))
                            .addGroup(panelBawahLayout.createSequentialGroup()
                                .addComponent(angka2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnTulip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelBawahLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBawahLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(labelWM, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        panelBawahLayout.setVerticalGroup(
            panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBawahLayout.createSequentialGroup()
                .addGroup(panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJasmine, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka1))
                .addGap(18, 18, 18)
                .addGroup(panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTulip, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka2))
                .addGap(29, 29, 29)
                .addGroup(panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnggrek, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka3))
                .addGap(35, 35, 35)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelWM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAtasLayout = new javax.swing.GroupLayout(panelAtas);
        panelAtas.setLayout(panelAtasLayout);
        panelAtasLayout.setHorizontalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtasLayout.createSequentialGroup()
                .addComponent(panelBawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(panelAtasLayout.createSequentialGroup()
                .addGroup(panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(judulKost, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAtasLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(roomlist, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAtasLayout.setVerticalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulKost, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomlist, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJasmineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJasmineActionPerformed
        // TODO add your handling code here:
        JasmineRoomNew JasmineR = new JasmineRoomNew ();
        JasmineR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJasmineActionPerformed

    private void btnTulipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTulipActionPerformed
        // TODO add your handling code here:
        TulipRoomNew Tulip = new TulipRoomNew ();
        Tulip.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTulipActionPerformed

    private void btnAnggrekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnggrekActionPerformed
        // TODO add your handling code here:
        AnggrekRoomNew Anggrek = new AnggrekRoomNew ();
        Anggrek.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnggrekActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         ListKostan kostan = new ListKostan();
        kostan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KostRedNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KostRedNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KostRedNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KostRedNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KostRedNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel angka1;
    private javax.swing.JLabel angka2;
    private javax.swing.JLabel angka3;
    private javax.swing.JButton btnAnggrek;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnJasmine;
    private javax.swing.JButton btnTulip;
    private javax.swing.JLabel judulKost;
    private javax.swing.JLabel labelWM;
    private javax.swing.JPanel panelAtas;
    private javax.swing.JPanel panelBawah;
    private javax.swing.JLabel roomlist;
    // End of variables declaration//GEN-END:variables
}
